name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_API_STORES_URI: ${{ secrets.REACT_APP_API_STORES_URI }}
          REACT_APP_API_DESTINATION_URI: ${{ secrets.REACT_APP_API_DESTINATION_URI }}
          REACT_APP_MAP_KEY: ${{ secrets.REACT_APP_MAP_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
